[package]
name = "eggwork-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
eggwork-core = { path = "../eggwork-core" }
eggfetch-core.workspace = true
serde_json.workspace = true
thiserror.workspace = true
serde.workspace = true
bytes.workspace = true
futures-util.workspace = true
url.workspace = true

[lints]
workspace = true
