[package]
name = "eggwork-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
eggwork-core = { path = "../eggwork-core" }
eggfetch-core.workspace = true
eggress-outbound = { workspace = true, optional = true }
serde_json.workspace = true
thiserror.workspace = true
serde.workspace = true
bytes.workspace = true
futures-util.workspace = true
url.workspace = true
tokio.workspace = true

[dev-dependencies]
eggress-testkit = "1.0.8"
rustls = "0.23"

[features]
default = []
eggress-route = ["dep:eggress-outbound", "eggfetch-core/advanced-routing"]

[lints]
workspace = true
