[package]
name = "eggwork-runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
eggwork-core = { path = "../eggwork-core" }
tokio = { workspace = true, features = ["net"] }
tokio-util.workspace = true
async-trait.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
landlock.workspace = true
tempfile.workspace = true

[dev-dependencies]

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["user"] }

[lints]
workspace = true
