[package]
name = "eggwork-runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
eggwork-core = { path = "../eggwork-core" }
tokio.workspace = true
tokio-util.workspace = true
async-trait.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[lints]
workspace = true
